.gitignore
src/App.js
src/pages/events/EventCreate.js
src/pages/events/EventShow.js
src/pages/events/EventSignIn.js
src/pages/events/Events.scss
src/pages/events/EventsIndex.js
src/pages/home/Home.js

added events pages

---

src/App.js
src/pages/semesters/SemesterCreate.js
src/pages/semesters/SemestersIndex.js

added semesters pages

---

src/App.js
src/pages/rankings/RankingsIndex.js
src/pages/rankings/SemesterRankings.js

added rankings pages

---

src/App.js
src/pages/login/LoginCreate.js
src/pages/login/LoginIndex.js

added login pages

---

package.json

uwp-32: adding proxy to package.json

---

src/pages/rankings/RankingsIndex.jsx
src/pages/rankings/SemesterRankings.jsx

uwp-34: displaying semester and rankings data

---

src/App.jsx
src/components/TermSelector/TermSelector.jsx
src/pages/members/MemberNew.jsx
src/pages/members/MemberShow.jsx
src/pages/members/MemberUpdate.jsx
src/pages/members/MembersIndex.jsx

uwp-36: creating user flows

---

src/App.jsx
src/pages/semesters/SemesterCreate.jsx
src/pages/semesters/SemestersIndex.jsx

uwp-35: adding both semester flows

---

src/pages/events/EventCreate.jsx
src/pages/events/EventShow.jsx
src/pages/events/EventSignIn.jsx
src/pages/events/EventsIndex.jsx
src/pages/members/MembersIndex.jsx

uwp-37: testing events pages functionality

---

public/index.html
src/components/Navbar/Navbar.tsx
src/components/TermSelector/TermSelector.tsx
src/types/index.d.ts
src/types/semester.d.ts

uwp-50: migrating general components to ts

---

src/constants.ts
src/pages/members/MemberEdit.tsx
src/pages/members/MemberNew.tsx
src/pages/members/MemberShow.tsx
src/pages/members/MembersIndex.tsx
src/pages/members/MembersTable.tsx
src/pages/rankings/RankingsIndex.tsx
src/pages/rankings/RankingsTable.tsx
src/pages/semesters/SemestersTable.tsx
src/types/index.d.ts
src/types/rankings.d.ts
src/types/user.d.ts

uwp-46: migrating members pages

---

src/pages/login/LoginCreate.tsx
src/pages/login/LoginIndex.tsx

uwp-55: migrating login pages

---

src/pages/members/MemberEdit.tsx
src/pages/members/MemberShow.tsx

uwp-6: centering form actions on members pages

---

src/pages/members/MembersIndex.tsx

uwp-5: fixing styling on members index buttons

---

src/pages/events/EventShow.tsx
src/pages/rankings/RankingsTable.tsx

uwp-9: adding place column to rankings table, fixing sign in bug

---

Dockerfile
docker-compose.yml
nginx/nginx.conf

Closes uwpokerclub/tickets#102

UWP-102 added nginx server to dockerfile

---

.github/workflows/publish.yml
.prettierignore

Closes uwpokerclub/tickets#112

uwp/112: adding cluster update step to publish

---

src/types/membership.d.ts
src/views/Admin/views/Semesters/components/SemestersTable.tsx
src/views/Admin/views/Semesters/views/NewMembership.tsx
src/views/Admin/views/Semesters/views/SemesterInfo.tsx

Closes uwpokerclub/tickets#118

tickets/118: added discounted checkbox and column

---

src/views/Admin/views/Semesters/views/SemesterInfo.tsx

Closes uwpokerclub/tickets#119

tickets/119: adding button to flip discounted state

---

src/types/entry.d.ts
src/views/Admin/views/Events/components/EntriesTable.tsx

Closes uwpokerclub/tickets#123

tickets/123: adding rebuy button to each entry

---

src/types/semester.d.ts
src/views/Admin/views/Semesters/views/NewSemester.tsx
src/views/Admin/views/Semesters/views/SemesterInfo.tsx
src/views/Admin/views/Semesters/views/style.scss

Closes uwpokerclub/tickets#122

tickets/122: adding info cards for semester stats

---

src/shared/components/Navbar/Navbar.tsx

Closes uwpokerclub/tickets#127

tickets/127: fixing hamburger menu on mobile

---

src/views/Admin/views/Events/views/EventDetails.tsx

Closes uwpokerclub/tickets#129

tickets/129: fixing search behavior on entries table

---

src/views/Admin/views/Users/views/ShowUser.tsx

Closes uwpokerclub/tickets#111

tickets/111: removing paid checkbox from user details page

---

src/views/Admin/views/Semesters/views/SemesterInfo.tsx
src/views/Admin/views/Semesters/views/style.scss

Closes uwpokerclub/tickets#130

tickets/130: adding search bar to membership list

---

src/shared/components/Navbar/Navbar.tsx

Closes uwpokerclub/tickets#142

tickets/142: remove redirect to /logout

---

src/types/membership.d.ts
src/views/Admin/views/Events/views/Events.scss
src/views/Admin/views/Events/views/RegisterEntries.tsx

Closes uwpokerclub/tickets#165

tickets/165: adding warning bg-color for non-free trial entries

---

src/types/membership.d.ts
src/views/Admin/views/Events/views/Events.scss
src/views/Admin/views/Events/views/RegisterEntries.tsx

Revert "tickets/165: adding warning bg-color for non-free trial entries"

---

Dockerfile
package.json
src/setupProxy.js
src/types/entry.d.ts
src/types/event.d.ts
src/types/membership.d.ts
src/types/rankings.d.ts
src/types/semester.d.ts
src/types/transaction.d.ts
src/types/user.d.ts
src/views/Admin/views/Events/components/EntriesTable.tsx
src/views/Admin/views/Events/views/EventDetails.tsx
src/views/Admin/views/Events/views/ListEvents.tsx
src/views/Admin/views/Events/views/NewEvent.tsx
src/views/Admin/views/Events/views/RegisterEntries.tsx
src/views/Admin/views/Rankings/components/RankingsTable.tsx
src/views/Admin/views/Rankings/views/SemesterCards.tsx
src/views/Admin/views/Rankings/views/SemesterRankings.tsx
src/views/Admin/views/Semesters/components/NewMembershipModal.tsx
src/views/Admin/views/Semesters/components/SemestersTable.tsx
src/views/Admin/views/Semesters/views/NewMembership.tsx
src/views/Admin/views/Semesters/views/SemesterInfo.tsx
src/views/Admin/views/Semesters/views/SemestersList.tsx
src/views/Admin/views/Users/components/UsersTable.tsx
src/views/Admin/views/Users/views/EditUser.tsx
src/views/Admin/views/Users/views/ListUsers.tsx
src/views/Admin/views/Users/views/ShowUser.tsx
tsconfig.json
yarn.lock

Closes uwpokerclub/tickets#185

tickets/185: fixing errors when using the Golang API

---

src/hooks/useFetch.ts
src/shared/utils/sendAPIRequest.ts
src/types/index.d.ts
src/views/Admin/views/Events/components/EntriesTable.tsx
src/views/Admin/views/Events/views/EventDetails.tsx
src/views/Admin/views/Events/views/ListEvents.tsx
src/views/Admin/views/Events/views/NewEvent.tsx
src/views/Admin/views/Events/views/RegisterEntries.tsx
src/views/Admin/views/Rankings/views/SemesterCards.tsx
src/views/Admin/views/Rankings/views/SemesterRankings.tsx
src/views/Admin/views/Semesters/components/NewMembershipModal.tsx
src/views/Admin/views/Semesters/views/NewMembership.tsx
src/views/Admin/views/Semesters/views/NewSemester.tsx
src/views/Admin/views/Semesters/views/SemesterInfo.tsx
src/views/Admin/views/Semesters/views/SemestersList.tsx
src/views/Admin/views/Users/views/EditUser.tsx
src/views/Admin/views/Users/views/ListUsers.tsx
src/views/Admin/views/Users/views/NewUser.tsx
src/views/Admin/views/Users/views/ShowUser.tsx
src/views/Login/views/NewLogin.tsx
src/views/Login/views/NewSession.tsx

Closes uwpokerclub/tickets#143

ticket/143: allow requests to a different URL based on environment variable

---

src/views/Admin/views/Semesters/views/NewSemester.tsx

Closes uwpokerclub/tickets#196

ticket/196: fixing errors when creating a new semester

---

src/types/semester.d.ts
src/views/Admin/views/Semesters/views/SemesterInfo.tsx

Closes uwpokerclub/tickets#199

ticket/199: fixing API request errors on semester info page

---

src/views/Admin/views/Events/views/EventDetails.tsx

Closes uwpokerclub/tickets#206

ticket/206: removing erenous / in request

---

src/views/Admin/views/Events/views/Events.scss
src/views/Admin/views/Events/views/RegisterEntries.tsx

Closes uwpokerclub/tickets#131

ticket/131: adding search bar to event registration list

---

src/views/Admin/views/Users/views/NewUser.tsx

Closes #478
Uses the existing alert banner to display an error above the user form:

ticket/478: add user already exists alert

---

src/types/index.d.ts
src/types/structures.d.ts
src/views/Admin/views/Events/views/Events.scss
src/views/Admin/views/Events/views/NewEvent.tsx

Adds and updates form fields on the event creation page
- Changes the `Format` field to a selector
- Adds a `Points Multiplier` field
- Adds a new section to select or create a blind structure
Closes #498

feat(structures): update event form to include structures and other changes

---

src/shared/components/ResponsiveNavbar/ResponsiveNavbar.tsx

feat: navbar now collapses after you click on a link

Collapse navbar

---

src/constants.ts

Fixes an issue where there was an ante for the 300/600 level when the ante should have been 0.
Fixes #529

fix: update ante from 600 to 0

---

src/views/Admin/views/Events/views/EventDetails.tsx

button to restart ended events, to fix points issues. 
closes #515

feat(event): button to restart ended events

---

src/shared/components/ResponsiveNavbar/ResponsiveNavbar.tsx
src/views/Main/components/ElectionEmbed.tsx
src/views/Main/components/Main.tsx
src/views/Main/views/Join/components/Join.tsx

Swaps the voting embed with the results embed on the elections page, as well as updates text in the join page and removes nav link.
Closes #584

feat(election): swap election embed to results embed

---

src/components/ResponsiveNavbar/ResponsiveNavbar.tsx
src/features/election/components/ElectionEmbed.tsx
src/features/socials-list/components/SocialsList.tsx
src/pages/Index.tsx

Updates/Removes links to the voting embed and replaces them with the results embed.
Closes #686

feat: publish results embed

---

nginx/templates/default.conf.template

Adds new security headers to the nginx config.
Closes #481

chore: update nginx header conf

---

src/contexts/auth/AuthProvider.tsx
src/features/login/components/CreateLogin.tsx
src/features/login/components/LoginForm.tsx
src/features/login/components/NewSession.tsx

Updates the API request on the login page to send a request to the new session based login route instead of the old JWT cookie route. 
Also, the AuthProvider context has been fixed to now search for the new name of the cookie instead of the old name
Closes #731

Update API request on login submission

---

src/contexts/auth/AuthProvider.tsx

Updates the functionality of the logout button to send a request to the
API session logout route.
Closes #730

Update logout button to send API request

---

src/pages/index.ts

Changed index.ts, added .tsx to the index import to ensure routing

fix: add '.tsx' to file routing for index file

---

index.html
package.json
public/root.css
src/components/Modal/Modal.module.css
src/components/Modal/Modal.tsx
src/features/events/components/EndEventModal.tsx
src/features/events/components/EventDetails.tsx
src/lib/sendRequest.ts
src/sdk/events/endEvent.ts
src/sdk/events/index.ts

Adds a new modal that is displayed when a user clicks the "End Event" button. Additionally some refactoring was done to make the Modal component more versatile, and the addition of a new SDK function for ending events.
Closes #743

End event confirmation modal

---

src/features/semesters/components/MembershipsTable.module.css
src/features/semesters/components/MembershipsTable.tsx

Makes two primary changes:
1. Makes the table responsive so it scrolls when on mobile devices
2. Updates the header bar to allow it to wrap when on mobile devices so
the search isn't shrunk.
Closes #755

Update memberships section to be responsive

---

src/features/events/components/EventRegister.tsx
src/features/rankings/components/DownloadRankingsButton.tsx
src/features/rankings/components/RankingsTable.tsx

Adds a new button above the rankings table to download the top 100 rankings as a CSV. Also updates the free trial count from 4 to 3.
Closes #778

feat: add download rankings button"

---

e2e-tests/cypress/e2e/events.cy.ts
package-lock.json
package.json
src/components/LoadingScreen/LoadingScreen.module.css
src/components/LoadingScreen/LoadingScreen.tsx
src/components/LoadingScreen/index.ts
src/components/index.ts
src/features/events/components/EditEventForm.module.css
src/features/events/components/EditEventForm.tsx
src/features/events/components/ListEvent.module.css
src/features/events/components/ListEvents.tsx
src/lib/sendRequest.ts
src/pages/Events.tsx
src/pages/events/EditEventPage.tsx

Implements a new page for editing events. Adds a new E2E test for this new page. Also adds a new loading screen component that can be used temporarily until we write our own customized loading component.
Closes #483

feat(events): added a new page to edit events

---

e2e-tests/cypress/e2e/memberships.cy.ts
package-lock.json
package.json
src/components/SelectSearch/SelectSearch.jsx
src/components/SelectSearch/components/Option.jsx
src/components/SelectSearch/components/Options.jsx
src/components/SelectSearch/index.d.ts
src/components/SelectSearch/index.js
src/components/SelectSearch/lib/classes.js
src/components/SelectSearch/lib/flattenOptions.js
src/components/SelectSearch/lib/fuzzySearch.js
src/components/SelectSearch/lib/getDisplayValue.js
src/components/SelectSearch/lib/getOption.js
src/components/SelectSearch/lib/getValue.js
src/components/SelectSearch/lib/groupOptions.js
src/components/SelectSearch/lib/highlight.js
src/components/SelectSearch/lib/isSame.js
src/components/SelectSearch/lib/isSelected.js
src/components/SelectSearch/lib/reduce.js
src/components/SelectSearch/lib/toArray.js
src/components/SelectSearch/lib/updateOption.js
src/components/SelectSearch/package.json
src/components/SelectSearch/style.css
src/components/SelectSearch/useHighlight.js
src/components/SelectSearch/useOptions.js
src/components/SelectSearch/useSelect.js
src/components/index.ts
src/features/semesters/components/NewMembershipModal.tsx

Fixes the display issue with the old react selector by removing it and implementing a custom one. It is from the `react-select-search` but that package doesn't support React v19 yet so I had to move it into this project.
Closes #783

fix(memberships): replace member selector in modal
